
import { PlaceHolderImagesMap } from './placeholder-images';

export const initialDestinations = [
  {
    name: 'Dharamshala',
    description: 'Home to the Dalai Lama, Dharamshala is a vibrant town known for its Tibetan culture, monasteries, and stunning views of the Dhauladhar range. A perfect blend of spirituality and natural beauty.',
    imageUrl: PlaceHolderImagesMap.get('dest-dharamshala')?.imageUrl,
    category: 'Spiritual & Cultural',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['McLeod Ganj', 'Namgyal Monastery', 'Bhagsu Nag Temple', 'Dal Lake'],
  },
  {
    name: 'Manali',
    description: 'A popular honeymoon and backpacking destination, Manali offers breathtaking views of snow-capped peaks, lush green valleys, and the gushing Beas River. It is a gateway to adventure sports and high-altitude Himalayan passes.',
    imageUrl: PlaceHolderImagesMap.get('dest-manali')?.imageUrl,
    category: 'Adventure & Honeymoon',
    bestTimeToVisit: 'October to June',
    attractions: ['Solang Valley', 'Rohtang Pass', 'Hadimba Temple', 'Old Manali'],
  },
  {
    name: 'Shimla',
    description: 'The former summer capital of British India, Shimla is a charming hill station with colonial architecture, a bustling mall road, and panoramic views. Its pleasant weather and accessibility make it a year-round destination.',
    imageUrl: PlaceHolderImagesMap.get('dest-shimla')?.imageUrl,
    category: 'Hill Station & Heritage',
    bestTimeToVisit: 'March to June, October to February (for snow)',
    attractions: ['The Ridge', 'Mall Road', 'Jakhoo Temple', 'Kufri'],
  },
  {
    name: 'Spiti Valley',
    description: 'A cold desert mountain valley, Spiti is a land of stark landscapes, ancient monasteries, and picturesque villages. It offers an unparalleled experience for those seeking raw, untouched nature and adventure.',
    imageUrl: PlaceHolderImagesMap.get('dest-spiti')?.imageUrl,
    category: 'Adventure & Remote',
    bestTimeToVisit: 'June to September',
    attractions: ['Key Monastery', 'Chandratal Lake', 'Kaza', 'Tabo Monastery'],
  },
  {
    name: 'Kangra',
    description: 'A vast and beautiful valley, Kangra is dotted with tea gardens, ancient forts, and temples. It provides a more serene and offbeat experience compared to other bustling tourist spots.',
    imageUrl: PlaceHolderImagesMap.get('dest-kangra')?.imageUrl,
    category: 'Nature & Heritage',
    bestTimeToVisit: 'September to June',
    attractions: ['Kangra Fort', 'Masroor Rock Cut Temple', 'Palampur Tea Gardens'],
  },
  {
    name: 'Bir Billing',
    description: 'Known as the paragliding capital of India, Bir Billing is a haven for adventure enthusiasts. It offers world-class facilities for tandem paragliding flights with stunning aerial views of the Dhauladhar mountains.',
    imageUrl: PlaceHolderImagesMap.get('dest-birbilling')?.imageUrl,
    category: 'Adventure Sports',
    bestTimeToVisit: 'March to May, October to November',
    attractions: ['Paragliding', 'Chokling Monastery', 'Gunehar Waterfall', 'Bir Tea Factory'],
  },
  {
    name: 'Palampur',
    description: 'The tea capital of northwest India, Palampur is famous for its lush tea gardens, pine forests, and mild climate. It offers a perfect retreat for nature lovers.',
    imageUrl: PlaceHolderImagesMap.get('dest-palampur')?.imageUrl,
    category: 'Nature & Tea Gardens',
    bestTimeToVisit: 'September to June',
    attractions: ['Tea Gardens', 'Neugal Khad', 'Baijnath Temple', 'Saurabh Van Vihar'],
  },
  {
    name: 'Chamba',
    description: 'Situated on the banks of the Ravi River, Chamba is known for its untouched natural beauty, ancient temples, and rich Pahari paintings and handicrafts.',
    imageUrl: PlaceHolderImagesMap.get('dest-chamba')?.imageUrl,
    category: 'History & Culture',
    bestTimeToVisit: 'March to June, September to December',
    attractions: ['Lakshmi Narayan Temple', 'Bhuri Singh Museum', 'Chamera Lake', 'Manimahesh'],
  },
  {
    name: 'Solan',
    description: 'Known as the "Mushroom City of India", Solan offers pleasant weather year-round. It is a great stopover with ancient temples and vibrant local culture.',
    imageUrl: PlaceHolderImagesMap.get('dest-solan')?.imageUrl,
    category: 'City & Culture',
    bestTimeToVisit: 'February to May, August to November',
    attractions: ['Shoolini Mata Temple', 'Jatoli Shiv Temple', 'Mohan Shakti Park', 'Kasauli (Nearby)'],
  },
  {
    name: 'Baglamukhi Temple',
    description: 'A dedicated temple to Goddess Baglamukhi, believed to grant victory over enemies. A spiritual center visited by devotees from all over.',
    imageUrl: PlaceHolderImagesMap.get('dest-baglamukhi')?.imageUrl,
    category: 'Spiritual & Pilgrimage',
    bestTimeToVisit: 'Year-round',
    attractions: ['Baglamukhi Temple', 'Bankhandi', 'Kangra Fort (Nearby)', 'Chintpurni Temple (Nearby)'],
  },
  {
    name: 'Bharmour',
    description: 'Ancient town with the sacred Chaurasi Temple complex consisting of 84 shrines. Gateway to the holy Manimahesh Lake pilgrimage in the Pir Panjal range.',
    imageUrl: PlaceHolderImagesMap.get('dest-bharmour')?.imageUrl,
    category: 'Spiritual & Heritage',
    bestTimeToVisit: 'April to October',
    attractions: ['Chaurasi Temple Complex', 'Manimahesh Temple', 'Bharmani Temple', 'Lakshana Devi Temple'],
  },
  {
    name: 'Kullu',
    description: 'The picturesque Kullu Valley is famous for its scenic beauty, Beas River, apple orchards, and adventure sports. Known as the gateway to Lahaul-Spiti and Manali.',
    imageUrl: PlaceHolderImagesMap.get('dest-kullu')?.imageUrl,
    category: 'Nature & Adventure',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Great Himalayan National Park', 'Raghunath Temple', 'Bijli Mahadev', 'Kasol Valley'],
  },
  {
    name: 'Pangi Valley',
    description: 'One of the most remote and unexplored valleys in Himachal Pradesh, Pangi offers dramatic landscapes, the Chandrabhaga River, and thrilling mountain roads.',
    imageUrl: PlaceHolderImagesMap.get('dest-pangi')?.imageUrl,
    category: 'Remote & Adventure',
    bestTimeToVisit: 'June to September',
    attractions: ['Killar', 'Sach Pass', 'Chandrabhaga River', 'Mindhal Lake'],
  },
  {
    name: 'Bilaspur',
    description: 'Home to the stunning Gobind Sagar Lake and Bhakra Dam, Bilaspur offers beautiful water views, boating, and a peaceful atmosphere away from crowded tourist spots.',
    imageUrl: PlaceHolderImagesMap.get('dest-bilaspur')?.imageUrl,
    category: 'Lake & Scenic',
    bestTimeToVisit: 'October to March',
    attractions: ['Gobind Sagar Lake', 'Bhakra Dam', 'Naina Devi Temple', 'Vyas Cave'],
  },
  {
    name: 'Narkanda',
    description: 'A charming hill station known for Hatu Peak, apple orchards, and skiing in winter. Offers panoramic views of snow-clad Himalayan peaks and peaceful pine forests.',
    imageUrl: PlaceHolderImagesMap.get('dest-narkanda')?.imageUrl,
    category: 'Hill Station & Winter Sports',
    bestTimeToVisit: 'December to February (for snow), March to June',
    attractions: ['Hatu Peak', 'Hatu Mata Temple', 'Skiing', 'Stokes Farm'],
  },
  {
    name: 'Kasauli',
    description: 'A serene colonial-era hill station nestled in the Himalayan foothills with pine forests, scenic viewpoints like Monkey Point, and heritage churches dating back to the British era.',
    imageUrl: PlaceHolderImagesMap.get('dest-kasauli')?.imageUrl,
    category: 'Hill Station & Heritage',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Monkey Point', 'Christ Church', 'Gilbert Trail', 'Sunset Point'],
  },
  {
    name: 'Dalhousie',
    description: 'A charming colonial hill station situated on five hills with beautiful views of the Pir Panjal and Dhauladhar ranges. Known for its pine-covered slopes and Victorian architecture.',
    imageUrl: PlaceHolderImagesMap.get('dest-dalhousie')?.imageUrl,
    category: 'Hill Station & Colonial',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Khajjiar', 'Dainkund Peak', 'Kalatop Wildlife Sanctuary', 'Panchpula'],
  },
  {
    name: 'Kasol',
    description: 'A backpacker\'s paradise in the beautiful Parvati Valley, famous for its Israeli cafes, scenic treks to Kheerganga and Tosh, and the gushing Parvati River.',
    imageUrl: PlaceHolderImagesMap.get('dest-kasol')?.imageUrl,
    category: 'Backpacking & Trekking',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Kheerganga Trek', 'Tosh Village', 'Chalal', 'Parvati River'],
  },
  {
    name: 'Khajjiar',
    description: 'Called the "Mini Switzerland of India", Khajjiar features a saucer-shaped meadow, a serene lake, and is surrounded by dense deodar forests with views of the Dhauladhar peaks.',
    imageUrl: PlaceHolderImagesMap.get('dest-khajjiar')?.imageUrl,
    category: 'Meadow & Scenic',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Khajjiar Lake', 'Khajji Nag Temple', 'Golden Devi Temple', 'Zorbing'],
  },
  {
    name: 'Kufri',
    description: 'A popular winter destination near Shimla known for skiing, snow activities, and yak rides. Home to the Himalayan Nature Park with diverse wildlife.',
    imageUrl: PlaceHolderImagesMap.get('dest-kufri')?.imageUrl,
    category: 'Winter Sports & Wildlife',
    bestTimeToVisit: 'November to February (for snow), March to June',
    attractions: ['Skiing', 'Himalayan Nature Park', 'Mahasu Peak', 'Fagu'],
  },
  {
    name: 'McLeod Ganj',
    description: 'Home to His Holiness the Dalai Lama and the Tibetan government-in-exile. A vibrant hub of Tibetan culture, Buddhist monasteries, cafes, and spiritual retreats.',
    imageUrl: PlaceHolderImagesMap.get('dest-mcleodganj')?.imageUrl,
    category: 'Spiritual & Cultural',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Dalai Lama Temple', 'Bhagsu Waterfall', 'Triund Trek', 'Tibetan Museum'],
  },
  {
    name: 'Tabo',
    description: 'An ancient monastery town in Spiti Valley housing the 1000-year-old Tabo Monastery, a UNESCO World Heritage candidate with priceless Buddhist murals and art.',
    imageUrl: PlaceHolderImagesMap.get('dest-tabo')?.imageUrl,
    category: 'Heritage & Spiritual',
    bestTimeToVisit: 'June to September',
    attractions: ['Tabo Monastery', 'Tabo Caves', 'Ancient Murals', 'Golden Temple'],
  },
  {
    name: 'Malana',
    description: 'A remote ancient village perched high in the Malana Nala, famous for its unique customs, ancient democratic system, and stunning mountain backdrop.',
    imageUrl: PlaceHolderImagesMap.get('dest-malana')?.imageUrl,
    category: 'Remote & Cultural',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Malana Village', 'Jamadagni Temple', 'Malana Dam', 'Trek to Chandrakhani Pass'],
  },
  {
    name: 'Kinnaur Valley',
    description: 'A scenic valley on the Indo-Tibetan border, famous for apple orchards, the sacred Kinner Kailash peak, ancient temples, and the dramatic Sutlej River gorge.',
    imageUrl: PlaceHolderImagesMap.get('dest-kinnaur')?.imageUrl,
    category: 'Scenic & Adventure',
    bestTimeToVisit: 'April to October',
    attractions: ['Kalpa', 'Kinner Kailash', 'Reckong Peo', 'Chitkul'],
  },
  {
    name: 'Chail',
    description: 'A peaceful hill station famous for having the world\'s highest cricket ground, the heritage Chail Palace, and a wildlife sanctuary with rich flora and fauna.',
    imageUrl: PlaceHolderImagesMap.get('dest-chail')?.imageUrl,
    category: 'Heritage & Wildlife',
    bestTimeToVisit: 'March to June, September to November',
    attractions: ['Chail Cricket Ground', 'Chail Palace', 'Chail Wildlife Sanctuary', 'Kali Ka Tibba'],
  },
].filter(dest => dest.imageUrl);
